repos:
-   repo: local
    hooks:
    -   id:  poetry-make-pretty
        name: make pretty
        entry: poetry run make pretty
        language: system
        types: [python]
        stages: [commit]